name: Release RemoteIO

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Pack files  
        run: |
          tar -czf remoteIO.tar.gz ./
          ls -lh

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: RemoteIO ${{ github.ref }}
          draft: false
          prerelease: false
    
      - name: Upload tar.gz
        uses: actions/upload-release-asset@v1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .
          asset_name: remoteIO.tar.gz
          asset_content_type: application/gzip
